# Generated by Django 4.2.6 on 2024-01-13 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='for_cart',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='orders_cart', to='user_profile.user_shopping_cart'),
        ),
    ]
